version: "3.9"  

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw   
      MYSQL_DATABASE: mydb                
      MYSQL_USER: myuser                  
      MYSQL_PASSWORD: myuserpass          
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql   

volumes:
  mysql_data:
